# Generated by Django 5.0.7 on 2024-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default='2024-08-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
